# Generated by Django 4.0 on 2022-02-22 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blog_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_file", models.ImageField(upload_to="")),
                (
                    "modified_file",
                    models.ImageField(blank=True, null=True, upload_to=""),
                ),
            ],
        ),
    ]
